export const myJSON = process.env.REACT_APP_API_JSON_URL;
export const API = process.env.REACT_APP_API_URL;
export const TEST = process.env.REACT_APP_API_URL_TEST;
export const API_FILE = process.env.REACT_APP_API_URL_FILE;
export const STOCK = process.env.REACT_APP_API_URL_MAC_STOCK;
export const MAC = process.env.REACT_APP_API_URL_MAC;
export const MAC_WS = process.env.REACT_APP_API_URL_MAC_WS;
export const API_WS = process.env.REACT_APP_API_URL_WS;
export const markerConfig = { enabled: false, states: { hover: { enabled: false } } }